name = "PaulStrings2"
uuid = "e8214510-4556-46a5-b53f-72884ec25a2d"
authors = ["John Lapeyre"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
